# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('public_repos', models.CharField(max_length=50)),
                ('private_repos', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
