# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0003_userdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.CharField(default=0, max_length=10000000),
        ),
    ]
