# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0012_auto_20180730_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
