# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0013_auto_20180730_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='image',
            new_name='avatar_url',
        ),
    ]
