# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0014_auto_20180730_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='avatar_url',
        ),
    ]
