# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0021_remove_userdetail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
