# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0023_apilogdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='private_repos',
        ),
    ]
