# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0024_remove_userdetail_private_repos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='avatar_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
