# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0025_auto_20180731_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='avatar_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
