# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0026_auto_20180731_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
