# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0027_auto_20180801_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
