# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('githubApi', '0028_auto_20180801_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='inserted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='public_repos',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
